apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  annotations:
    prometheus.io/scrape: "true" # Enable scraping
    prometheus.io/port: "5000" # Port where the API exposes metrics
    prometheus.io/path: "/metrics" # Path to the metrics endpoint
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
          ports:
            - name: api-port
              containerPort: 5000 

                  