apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: jenkins-secrets-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: jenkins-secrets-rolebinding
subjects:
  - kind: ServiceAccount
    name: myjenkins
    namespace: default
roleRef:
  kind: Role
  name: jenkins-secrets-role
  apiGroup: rbac.authorization.k8s.io
