apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  annotations:
    prometheus.io/scrape: "true" # Enable scraping
    prometheus.io/port: "80" # Port where metrics are exposed
    prometheus.io/path: "/metrics"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
          - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-url-configmap
              key: REACT_APP_BACKEND_URL
