apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-argocd
  namespace: argocd
  annotations:
    # List the images to be tracked
    argocd-image-updater.argoproj.io/image-list: "danbit2024/frontend,danbit2024/backend"
    # Explicitly map each image to the corresponding Helm values key
    argocd-image-updater.argoproj.io/frontend.image: "danbit2024/frontend"
    argocd-image-updater.argoproj.io/backend.image: "danbit2024/backend"
    # Specify where the updated image tags should be written
    argocd-image-updater.argoproj.io/frontend.image.tag: "frontend.image.tag"
    argocd-image-updater.argoproj.io/backend.image.tag: "backend.image.tag"
    # Set write-back method (git in this case)
    argocd-image-updater.argoproj.io/write-back-method: "git"
spec:
  project: default
  sources:
    - repoURL: "registry-1.docker.io/danbit2024"
      chart: helm-reactapp
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/helm-reactapp/values.yaml
        version: v3
    - repoURL: "https://gitlab.com/sela-tracks/1109/students/danielbit/final-project/application/react-app.git"
      targetRevision: HEAD
      path: helm-reactapp
      helm:
        valueFiles:
          - helm-reactapp/values.yaml
  destination:
    namespace: app
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
