apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/sela-tracks/1109/students/danielbit/final-project/application/react-app.git
    targetRevision: HEAD
    path: helm-reactapp/
  destination:
    server: https://kubernetes.default.svc
    namespace: deployment
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
