apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
  labels:
    app: reactapp-agent
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker

    - name: nodejs
      image: node:16
      command:
        - sleep
      args:
        - infinity
      imagePullPolicy: Always
      securityContext:
        privileged: false

    - name: python-test
      image: python:3.9-slim
      command:
        - sleep
      args:
        - infinity
      imagePullPolicy: Always
      securityContext:
        privileged: false
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: docker
      image: docker:latest
      command:
        - sleep
      args:
        - infinity
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: workspace-volume
          mountPath: /home/jenkins/agent

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: workspace-volume
      emptyDir: {}
